apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80         # Port du Service
      targetPort: 8888 # Port du conteneur
  type: NodePort        # Pour exposer sur un port du Node

